[package]
name = "lunr"
version = "0.1.0"
authors = ["seanBE <SeanBE@users.noreply.github.com>"]
edition = "2018"

[dependencies]
scraper = "0.9.1"
walkdir = "2.2.7"
serde = "1.0.87"
serde_json = "1.0.38"
serde_derive = "1.0.87"
